#!/usr/bin/python3
"""Module to execute functions"""

import urllib.request

if __name__ == "__main__":
    req = urllib.request.Request('https://intranet.hbtn.io/status0')
    with urllib.request.urlopen(req) as response:
        html = response.read()
        print(html)

#    with urllib.request.urlopen('https://intranet.hbtn.io/status0') as response:
#        print(response.read())
#    req = urllib.request.urlopen('https://intranet.hbtn.io/status')
#    with urllib.request.urlopen(req) as response:
#        for i in response:
#            print(i)
